//web.cpp

#include "web.h"

String html;

String SendHTML(float pH, float PPM, float suhu, float tinggi_cm, String kondisiOtomatisasi){ 
html = "<!DOCTYPE html> <html>\n";
html += "<head><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\n";
html += "<title>Dashboard</title>\n";
html += "<style>html { font-family: Helvetica, Arial, sans-serif; display: inline-block; margin: 0px auto; text-align: center; background-color: var(--color1);transition: background-color 0.3s ease, color 0.3s ease;}\n";
html += ".light-theme {--color1 : #f4f4f9;--color2 : #444444;--color3 : #666666;--color4 : #444444;--color5 : #ffffff;--color6 : #dddddd;--color7 : #ffffff;--color8 : #dddddd;--color9 : #4CAF50;--color10 : white;--color11 : #45a049;--color12 : #ffffff;--color13 : #dddddd;--color14 : #f0f0f0;}\n";
html += ".dark-theme {--color1 : #1a1a1a;--color2 : #8a2be2;--color3 : #8a2be2;--color4 : #dcdcdc;--color5 : #555555;--color6 : #dcdcdc;--color7 : #555555;--color8 : #dcdcdc;--color9 : #8a2be2;--color10 : #dcdcdc;--color11 : #7a1db3;--color12 : #8a2be2;--color13 : #dcdcdc;--color14 : #7a1db3;}\n";
html += "body { margin-top: 50px; color: #333; }\n";
html += "body.light-theme {background-color: var(--color1);}\n";
html += "body.dark-theme {background-color: var(--color1);}\n";
html += "h1 { color: var(--color2); margin: 50px auto 30px; font-size: 2rem; }\n";
html += "h2 { color: var(--color3); margin: 30px auto 20px; font-size: 1.5rem; }\n";
html += "p { font-size: 1.2rem; color: var(--color4); margin-bottom: 10px; }\n";
html += ".sensor-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; max-width: 500px; margin: 20px auto; }\n";
html += ".sensor-box { background-color: var(--color5); border: 1px solid var(--color6); border-radius: 10px; padding: 20px; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1); }\n";
html += ".status-box, .control-box { background-color: var(--color7); border: 1px solid var(--color8); border-radius: 10px; padding-bottom: 20px;; margin: 20px auto; width: 100%; max-width: 500px; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1); }\n";
html += ".status-box p, .control-box p { font-size: 1.2rem; font-weight: bold; }\n";
html += ".control-box button { background-color: var(--color9); border: none; color: var(--color10); padding: 15px 30px; font-size: 1rem; cursor: pointer; border-radius: 5px; box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1); transition: background-color 0.3s ease; }\n";
html += ".control-box button:hover { background-color: var(--color11); }\n";
html += ".theme-switch {position: fixed;top: 10px;right: 10px;padding: 5px 5px;background-color: var(--color12);opacity: 0.3;border: 1px solid var(--color13);border-radius: 5px;cursor: pointer;font-size: 1rem;color: var(--color4);transition: background-color 0.3s ease;}\n";
html += ".theme-switch:hover {background-color: var(--color14);}\n";
html += "</style>\n";
html += "</head>\n";
html += "<body class=\"light-theme\">\n";
html += "<h1>Sistem Monitoring Nutrisi Otomatis</h1>\n";
html += "<div id=\"webpage\">\n";
html += "<h2>Pembacaan Sensor</h2>\n";
html += "<div class=\"sensor-grid\">\n";
html += "<div class=\"sensor-box\">\n";
html += "<p><strong>pH</strong> : <span id=\"pH\">";
html += pH;
html += "</span></p>\n";
html += "</div>\n";
html += "<div class=\"sensor-box\">\n";
html += "<p><strong>PPM</strong>: <span id=\"PPM\">";
html += PPM;
html += "</span></p>\n";
html += "</div>\n";
html += "<div class=\"sensor-box\">\n";
html += "<p><strong>Suhu</strong>: <span id=\"suhu\">";
html += suhu;
html += "</span> <sup>o</sup>C</p>\n";
html += "</div>\n";
html += "<div class=\"sensor-box\">\n";
html += "<p><strong>Tinggi Air</strong>: <span id=\"tinggi_cm\">";
html += tinggi_cm;
html += "</span> cm</p>\n";
html += "</div>\n";
html += "</div>\n";
html += "<div class=\"status-box\">\n";
html += "<p><strong>Kondisi Otomatisasi:</strong> <br> <span id=\"kondisiOtomatisasi\">";
html += kondisiOtomatisasi;
html += "</span></p>\n";
html += "</div>\n";
html += "</div>\n";
html += "<h2>Kontrol Sistem</h2>\n";
html += "<div id=\"saklar\" class=\"control-box\">\n";
html += "<p>Saklar Otomatisasi</p>\n";
html += "<button onclick=\"control('/otomatisasi_on')\">ON</button>\n";
html += "</div>\n";
html += "<div class=\"theme-switch\" onclick=\"toggleTheme()\">Ganti Tema</div>\n";
html += "<script>\n";
html += "function control(endpoint) {\n";
html += "  fetch(endpoint)\n";
html += "    .then(response => response.text())\n";
html += "    .then(data => {\n";
html += "      console.log(data);\n";
html += "    });\n";
html += "}\n";
html += "function toggleTheme() {\n";
html += "      const body = document.body;\n";
html += "      const currentTheme = body.classList.contains('light-theme') ? 'light-theme' : 'dark-theme';\n";
html += "      body.classList.toggle('light-theme', currentTheme === 'dark-theme');\n";
html += "      body.classList.toggle('dark-theme', currentTheme === 'light-theme');\n";
html += "      const buttonText = body.classList.contains('dark-theme') ? 'Tema Terang' : 'Tema Gelap';\n";
html += "      document.querySelector('.theme-switch').textContent = buttonText;\n";
html += "    }\n";
html += "setInterval(() => {\n";
html += "  fetch('/data')\n";
html += "    .then(res => res.json())\n";
html += "    .then(data => {\n";
html += "      document.getElementById('pH').textContent = data.pH;\n";
html += "      document.getElementById('PPM').textContent = data.PPM;\n";
html += "      document.getElementById('suhu').textContent = data.suhu;\n";
html += "      document.getElementById('tinggi_cm').textContent = data.tinggi_cm;\n";
html += "      document.getElementById('kondisiOtomatisasi').textContent = data.kondisiOtomatisasi;\n";
html += "    });\n";
html += "}, 3000);\n";
html += "</script>\n";
html += "</body>\n";
html += "</html>\n";

return html; 
}
